### PR TITLE
File size.

### PR DESCRIPTION
**Pull request by K0-RR**
I optimized icons.
The one for the repo is compressed losslessly and the one in the jar in lossy - reduced color palette to 256 but I don't see any differences unless when zoomed to max.
This should reduce the jar size from ~110 KB to ~30 KB.

### CODE REVIEW

**Comment by Szum123321** [comment]
And repair fabric.mod.json

**Comment by K0-RR** [comment]
I'm sorry for making these mistakes, I was doing a few prs at once and somehow managed to fuck this one. Also added the CurseForge link to the repo Readme file.

**Comment by Szum123321** [comment]
Sorry but I think it's better to add links in readme in the form of clickable shields. I'll add that later. For now please change it back (readme.md). Besides that, thank you!

**Comment by K0-RR** [comment]
Reverted!

**Pull request merged**
